### ISSUE TITLE
Should all "Sign Languages" use Zxxx script?

### ISSUE THREAD

**Issue by darcywong00** [silnrsi/langtags#10]
I've been updating langtags.json used for Speech Analyzer, and am filtering out the "Sign Language" languages.
Shouldn't they all use `Zxxx` for the script?

In langtags.csv, I'm seeing "Solomon Islands Sign Language" with `Latn` script.

```
szs,szs-Latn-SB,Solomon Islands Sign Language,SB,,,,,1,,,MEL,szs,LE,30-Oct-2018,
szs-Zxxx,szs-Zxxx-SB,Solomon Islands Sign Language,SB,,,,,,,,MEL,szs,LE,30-Oct-2018,
```

**Comment by darcywong00** [comment]
Well, I see some other Sign Language tags that don't use `Zxxx`. But maybe `szs-Latn-SB` is incorrect?
Same question for `ads-Latn-GH`.

**Comment by LornaSIL** [comment]
Yes, both of those should be deleted (szs-Latn-SB and ads-Latn-GH) and szs-Zxxx will become `szs` and `ads-Zxxx` will become `ads`. Those were mistakes I made when I decided all languages in Ghana and Solomon Islands would likely be written with Latin script. I made the change in the source langtags.csv. It will eventually filter do langtags.json.

If you spot Sign Language tags that don't use `Zxxx`, let me know. There are some that do have a written form (like Sign Writing and Stokoe Notation) so there should be 2+ entries for those.

**Comment by darcywong00** [comment]
> If you spot Sign Language tags that don't use Zxxx, let me know. There are some that do have a written form (like Sign Writing and Stokoe Notation) so there should be 2+ entries for those.

Is this the Stokoe Notation?

```json
{
        "full": "bfi-Zzzz-GB-x-stokoe",
        "iana": [ "British Sign Language" ],
        "iso639_3": "bfi",
        "name": "British Sign Language",
        "names": [ "BSL" ],
        "nophonvars": true,
        "region": "GB",
        "regionname": "United Kingdom",
        "script": "Zzzz",
        "sldr": false,
        "tag": "bfi-Zzzz-x-stokoe",
        "tags": [ "bfi-GB-x-stokoe", "sgn-bfi-GB-x-stokoe" ],
        "windows": "bfi-Zzzz-x-stokoe"
    },
```

The other Sign Language tag I saw not using `Zxxxx` was:

```json
{
        "full": "ase-Sgnw-US",
        "iana": [ "American Sign Language" ],
        "iso639_3": "ase",
        "name": "American Sign Language",
        "names": [ "#A-S-L", "ASL", "Ameslan", "Benin Sign Language", "Burkina Faso Sign Language", "Francophone ASL", "Gabonese Sign Language", "Haitian Sign Language", "LSAF", "LSAF Ivoirienne", "LSCI", "LSFA", "LSH", "Langue des signes américaine", "Langue des signes congolaise", "Langue des signes de Côte d’Ivoire", "Langue des signes de l’Afrique francophone", "Langue des signes du Congo", "Langue des signes d’Afrique francophone", "Langue des signes franco-africaine", "Langue des signes haïtienne", "Malian ASL", "SIGN AMERICA", "Togo Sign Language" ],
        "region": "US",
        "regionname": "United States",
        "regions": [ "AG", "BB", "BF", "BJ", "BM", "BO", "BS", "BZ", "CA", "CF", "CG", "CI", "DM", "GA", "GD", "GU", "GY", "HT", "JM", "KN", "KY", "LC", "ML", "NG", "PH", "PR", "SV", "TD", "TG", "TT", "VC", "VI", "ZA", "ZM" ],
        "script": "Sgnw",
        "sldr": false,
        "tag": "ase",
        "tags": [ "ase-Sgnw", "ase-US", "sgn-ase", "sgn-ase-US" ],
        "windows": "ase-Sgnw"
    },
```

where there's also `ase-Zxxx-US`

**Comment by LornaSIL** [comment]
Zxxx is a "Signed Language" - not written
Sgnw is Sign Writing which is little figures. I should probably add other languages that use it.
Stokoe is not recognized by ISO 15924 as a writing system, but it is a collection of symbols used to write some language. The symbols look very much like math symbols, etc. `x-stokoe` is appropriate and I should probably add the other languages I know that use it.
It looks like there is an `ase-Zxxx-US` in the source `langtags.csv`. If it's not in langtags.json that would be a bug.
Similarly, there is a `bfi-Zxxx-GB` in `langtags.csv`

**Comment by darcywong00** [comment]
OK. Does this mean
"British Sign Language" should use `bfi-Zxxx-GB-x-stokoe` instead of `bfi-Zzzz-GB-x-stokoe`,
and `ase-Sgnw-US` should be named "American Sign Writing"?

**Comment by LornaSIL** [comment]
No, because bfi is also written...and it uses Stokoe Notation which does not have an official script code yet. So, `bfi-Zzzz-GB-x-stokoe` is accurate.

ase is also written using Sign Writing which has its own script code `Sgnw`.

**Comment by LornaSIL** [comment]
No, to both. Stokoe is not encoded, thus Zzzz.
ase uses both signing and also Sign Writing which is encoded.
