### ISSUE TITLE
Missing Ethnologue and ISO 639-3 languages

### ISSUE THREAD

**Issue by LornaSIL** [silnrsi/langtags#2]
We need to add in the following Ethnologue languages that are missing:

gie,gie-Qaax-CI,Guébie,Qaax,CI,CI,,1,,WAF,gie,,,,,,
npx,npx-Latn-SB,Noipä,Latn,SB,SB,,1,,MEL,npx,,,,,,
pbm,pbm-Latn-MX,"Mazatec, Puebla and Northeastern",Latn,MX,MX,,1,,CAM,pbm,,,,,,
szs,szs-Latn-SB,Solomon Islands Sign Language,Latn,SB,SB,,1,,MEL,szs,,,,,,
wbs,wbs-Zyyy-IN,West Bengal Sign Language,Zyyy,IN,IN,,1,,MEL,wbs,,,,,,

We need to add in the following ISO 639-3 languages that are missing:
dno,dno-Latn-CD,"Ndrulo, Northern Lendu",Latn,CD,CD,,1,,MAF,dno,,,,,,
dwz,dwz-Qaax-NP,Dewas Rai,Qaax,NP,NP,,1,,SAS,dwz,,,,,,

**Comment by mhosken** [comment]
Just a quick note to say that I haven't cut the cord to the Google sheet
yet. So feel free to make edits there. They will end up in GitHub. I'll
announce when I'm going to cut the cord. Probably end of this week. I'm
really close with diffted. It can almost make GitHub commits. Then it just
needs packaging for Windows and we can deploy, etc. At that point, when we
cut the cord, I'll strip the columns and sort the data and we can go with
GitHub as the authority.

GB,
Martin
