### ISSUE TITLE
Enhanced Readme?

### ISSUE THREAD

**Issue by hatton** [silnrsi/langtags#6]
This is a really helpful resource. I wonder if you could make it even more helpful by enhancing the readme to convey the following:

* What is a "lang tag". (I *think* it something that conforms to BCP 47)
* What are the sources of this data?
* If someone wants a new tag added, what is the correct process to go through?
* What is the "published" file that projects should use? E.g. https://raw.githubusercontent.com/silnrsi/langtags/release/pub/langtags.json

Less vital, but a helpful:
* Explain that there are, shall we say, *metadata* entries where the tags that start with "_" which should be ignored.
* A short description of what each field needs. They are probably all obvious to the creators, but not to use consumers. For example, I don't know what `nophonvars` is. And it would be helpful to say that `sldr: true` means it is covered by [this other repo](https://github.com/silnrsi/sldr) (if that's in fact what it means).
* Please clarify the relationship between `tag` and `tags`, beyond the obvious that the later is an array.

Thanks!

**Comment by mhosken** [comment]
I hope the minor changes to the readme to point to the relevant documents will give you what you need.

**Comment by DavidLRowe** [comment]
@hatton Thanks for taking the time to raise this issue. Please review and either close the issue, or tell us what we missed.

**Comment by hatton** [comment]
Excellent, thanks.
